### PR TITLE
Import Gerrit commit history from GE main repo

### PR DESCRIPTION
**Pull request by mast-eu**
Commits have been extracted from https://github.com/gitextensions/gitextensions/master as follows:

```
git subtree split --prefix=Plugins/Gerrit --annotate="(split from main repo) " --branch GE_Plugins_Gerrit
git subtree split --prefix=UnitTests/Plugins/Gerrit.Tests --annotate="(split from main repo) " --branch GE_UnitTests_Plugins_Gerrit.Tests
git subtree split --prefix=UnitTests/Plugins/GerritTests --annotate="(split from main repo) " --branch GE_UnitTests_Plugins_GerritTests
```
and merged accordingly.

* The commits' metadata, like original author name, date and commit message, has been preserved.
* Many extracted commits modified also other files (not related to the Gerrit plugin). These changes are automatically removed by `git subtree split`, since they are not relevant for extracting the plugin. Due to this, some of the commit messages might be not 100% accurate anymore.
* The code is copied as-is from the main repo. The scope of this PR is only to import the history. I will prepare a separate PR to update the VS solution, set-up CI, cleanup, etc.

### CODE REVIEW

**Comment by gerhardol** [comment]
Why not use _filter-branch_ or _subtree split_?

**Comment by RussKie** [comment]
🤔 I'm not sure Martin, I would think you'd do what Gerhard said...
How about we follow ➡️  https://help.github.com/en/github/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by mast-eu** [comment]
First I was trying to use _filter-branch_ or _subtree split_, but they work only on a single folder, as far as I know. However, I want to extract the history of 2 folders, `Plugins/Gerrit` and `UnitTests/Plugins/Gerrit.Tests`. Actually 3, because there's also
  `UnitTests/Plugins/GerritTests` (without the dot) and both git commands don't follow folder renames.

I can leverage _git subtree split_ on the 3 folders, basically creating 3 unrelated histories, and then merge them accordingly.

**Comment by RussKie** [comment]
👍

**Comment by mast-eu** [comment]
Updated, please have a look.

**Comment by RussKie** [comment]
Nice job!

Btw we have received a release from @pvginkel so I think we're in a position to change to licence to MIT.

**Comment by RussKie** [comment]
🎉

**Pull request merged**
