### PR TITLE
switch from GPLv3 to MIT license

### PR DESCRIPTION
**Pull request by mast-eu**
Change the license to MIT (based on https://github.com/gitextensions/GitExtensions.GerritPlugin/pull/1#issuecomment-583706425).

### CODE REVIEW

**Comment by RussKie** [comment]
We have a release from @pvginkel, the author of the plugin:
image

**Comment by RussKie** [comment]
I think we should retain the contributors.txt as it contains the contributors releases of the code under the MIT licence.

**Comment by mast-eu** [comment]
> I think we should retain the contributors.txt

Ok, I will update PR the next time I get on a PC.

**Comment by mast-eu** [comment]
Updated.

**Pull request merged**
