### PR TITLE
Add branch dropdown & fix default branch value (#34)

### PR DESCRIPTION
**Pull request by lekhmanrus**
- [x] changed branch text field to dropdown
- [x] fixed bug with default branch name value (#34)

### CODE REVIEW

**Comment by lekhmanrus** [comment]
Not clear to me, why integration tests can't find Git Extensions' DLLs. Any thoughts?
Looks like it was cached or kind of.

**Comment by RussKie** [comment]
> Not clear to me, why integration tests can't find Git Extensions' DLLs. Any thoughts?
> I suppose, that is because of new version of Git Extensions v**3.6.0.12716**-[gitextensions/gitextensions@5504d63](https://github.com/gitextensions/gitextensions/commit/5504d634dcf54a4c9a7921b0a07ceafeb4b3c37a).

I don't use this plugin at all, so I can only speculate. 
The current version of the plugin is built and designed for Git Extensions < v3.6 to run under .NET Framework:
https://github.com/gitextensions/GitExtensions.GerritPlugin/blob/821178b1f25aade72537639000a015a419928934/Directory.Build.props#L18
The current master of Git Extensions is targeting .NET 5.0, and the build fails.

This looks how we configure which artifact to build against but I have no idea how it works...
https://github.com/gitextensions/GitExtensions.GerritPlugin/blob/821178b1f25aade72537639000a015a419928934/src/GitExtensions.GerritPlugin/GitExtensions.GerritPlugin.csproj.user#L3-L12

@mast-eu do you remember how it all hangs together?

**Comment by RussKie** [comment]
I suspect this script gets invoked https://github.com/gitextensions/gitextensions.extensibility/blob/master/src/GitExtensions.Extensibility/tools/Download-GitExtensions.ps1 during the build, and downloads the right version.

**Comment by RussKie** [comment]
Nevermind, I think I worked it out.

**Review by RussKie — APPROVED** [review]
I don't use Gerrit so can't verify whether this change is correct or not. The changeset itself looks ok.

**Comment by RussKie** [comment]
Published here: https://www.nuget.org/packages/GitExtensions.GerritPlugin/1.2.0.76

**Comment by lekhmanrus** [comment]
@RussKie, thanks! Just upgraded Gerrit on my machine - works fine. 🙂

**Pull request merged**
