### PR TITLE
Download patchset (#39)

### LINKED ISSUE #39: Missing patchset number in branch name after download
**Do you want to request a feature or report a bug?**
bug/feature

**What is the current behavior?**
If you use the green button to download the change from gerrit with the change number, a branch in the following format is created:
review/[username]/[Change Number]

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
If a change gets a new patchset from an other person and i want to fetch the patchset when the branch is still checked out, this is not possible, because the branch name already exists.
If the branch is not checked out, the older patchset gets locally lost.

**What is the expected behavior?**
New branch name for every patchset. For example in the following format:
review/[username]/[Change Number]/[Patchset number]
(If no patchset number could be selected, then the newest should be used.)

**Environment you encounter the issue:**

    GitExtensions.GerritPlugin v1.2.0.76
    Git Extensions 3.5.4.12724
    Build 65f01f39982ccb121c4df7d4b00b506939553958
    Git 2.33.0.windows.2
    Microsoft Windows NT 10.0.19042.0
    .NET Framework 4.8.4300.0
    DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
N/A

### PR DESCRIPTION
**Pull request by lekhmanrus**
- [x] closes #39
- [x] adds ability to download specific patchset - not the latest/current only, as before.

image

### CODE REVIEW

**Comment by RussKie** [comment]
I sent your an invite to this repo that'll make you a maintainer. You can reach you on my email if you have any questions.

**Comment by lekhmanrus** [comment]
> Is this addressing #27 and #28 as well as #39?

yep, it is combining all 3 commits/pull requests

**Comment by RussKie** [comment]
LGTM, but I don't use Gerrit or the plugin, and have an real opinion. Feel free to merge.

. . .

> image

You may wish to consider to move the 'help' text under textboxes into (i) buttons like we use in Settings:
image
https://github.com/gitextensions/gitextensions/blob/3d4ed902fcd13dba41d66dd1e6b918ba78eac3f5/GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs#L54


Also once the template is updated to .NET 5.0+ you may be able to use [`PlaceHolderText`](https://docs.microsoft.com/dotnet/api/system.windows.forms.textbox.placeholdertext).

**Comment by lekhmanrus** [comment]
Now it looks like this:
image

**Pull request merged**
