### PR TITLE
Upgrade dependencies and release v2.0.6

### PR DESCRIPTION
**Pull request by lekhmanrus**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Build related changes
- [x] Documentation
- [ ] Other: 

## What is the new behavior?
Upgraded some dependencies, did small code refactoring and released a new version.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by lekhmanrus** [comment]
Hey @maraf, 
Any idea why we can have error 403 in AppVeyor? It works fine locally, Is there anything related to gitextensions.extensibility?
Thanks!

**Comment by maraf** [comment]
No idea, I restarted it and it passed 🤷‍♂️

**Comment by gerhardol** [comment]
AppVeyor builds are not always stable...

**Comment by mstv** [comment]
> requested a review from mstv

Sorry, plugins and particularly Gerrit is not my field. I just identified the cause of the incompatibility.
Could you review, @gerhardol?

**Review by gerhardol — APPROVED** [review]
Not a Gerrit user, have not run.
Did not see any issues in a not too thorough review.

Sorry I missed this, I do not feel I contribute to the plugin.
But I may function as a gatekeeper to filter hostile commits, if this is that it is extremely well hidden as well as @lekhmanrus as a maintainer

**Pull request merged**
